### ISSUE TITLE
can use qt widget?

### ISSUE THREAD

**Issue by reionwong** [ubports/qtubuntu#2]
Can you use the qt widget to develop applications under ubuntu touch?

**Comment by sverzegnassi** [comment]
I guess nobody has really digged into this during these years, since Canonical has always supported only the development of QML apps, and the UI of QtWidgets apps don't integrate well with the rest of the OS.

I quickly tried to build one of those QtWidgets demo available in the Qt documentation.
Tbh, I don't know which are the Qt packages that comes preinstalled with the OS, however everything seems to work well.
Short answer is that it should be possible, but it might be required to ship certain libraries within the .click package.

This is the [code of the reference demo](https://github.com/sverzegnassi/ubuntu-touch-qtwidgets-calculator-demo), based on the "QtQuick App with QML UI (qmake)" template available in the Ubuntu IDE.

![image](https://user-images.githubusercontent.com/1218443/30836780-b5e17bce-a260-11e7-8ec9-62973f336100.png)

**Comment by reionwong** [comment]
thx.
